import image6 from "/images/questions/question1.png";

export const questions = [
  {
    testId: "test001",
    id: 1,
    question: "What is the capital of France?",
    options: {
      a: "Berlin",
      b: "Madrid",
      c: "Paris",
      d: "Rome",
    },
    answer: "c",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 2,
    question: "Which data structure uses FIFO?",
    options: {
      a: "Stack",
      b: "Queue",
      c: "Tree",
      d: "Graph",
    },
    answer: "b",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 3,
    question: "Which keyword is used to define a constant in JavaScript?",
    options: {
      a: "let",
      b: "var",
      c: "constant",
      d: "const",
    },
    answer: "d",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 4,
    question: "Which protocol is used for secure HTTP connections?",
    options: {
      a: "FTP",
      b: "SSH",
      c: "TLS",
      d: "TCP",
    },
    answer: "c",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 5,
    question: "What does CSS stand for?",
    options: {
      a: "Cascading Style Sheets",
      b: "Creative Style Syntax",
      c: "Computer Style Sheet",
      d: "Colorful Style Sheet",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 6,
    question:
      "What is the regular expression for the automaton shown in the image?",
    options: {
      a: "0*1+",
      b: "0* + 0*1+",
      c: "1*0+",
      d: "(0+1)*",
    },
    answer: "b",
    imageUrl: image6,
  },
  {
    testId: "test001",
    id: 7,
    question:
      "Which of the following is not a primitive data type in JavaScript?",
    options: {
      a: "String",
      b: "Number",
      c: "Boolean",
      d: "Array",
    },
    answer: "d",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 8,
    question: "Which HTML tag is used to define an unordered list?",
    options: {
      a: "<ul>",
      b: "<ol>",
      c: "<li>",
      d: "<list>",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 9,
    question: "What does SQL stand for?",
    options: {
      a: "Structured Query Language",
      b: "Simple Query Language",
      c: "Sequential Query Language",
      d: "Standard Query Language",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 10,
    question: "Which sorting algorithm has the best average time complexity?",
    options: {
      a: "Bubble Sort",
      b: "Selection Sort",
      c: "Merge Sort",
      d: "Insertion Sort",
    },
    answer: "c",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 11,
    question: "Which HTTP method is used to update a resource?",
    options: {
      a: "GET",
      b: "POST",
      c: "PUT",
      d: "DELETE",
    },
    answer: "c",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 12,
    question: "Which of the following is a JavaScript framework?",
    options: {
      a: "Django",
      b: "React",
      c: "Laravel",
      d: "Flask",
    },
    answer: "b",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 13,
    question: "Which HTML attribute is used to define inline styles?",
    options: {
      a: "class",
      b: "style",
      c: "font",
      d: "styles",
    },
    answer: "b",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 14,
    question: "Which company developed the React library?",
    options: {
      a: "Google",
      b: "Facebook",
      c: "Microsoft",
      d: "Twitter",
    },
    answer: "b",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 15,
    question: "Which symbol is used for single-line comments in JavaScript?",
    options: {
      a: "//",
      b: "/*",
      c: "#",
      d: "<!--",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 16,
    question: "Which HTML tag is used to display a picture on a webpage?",
    options: {
      a: "<img>",
      b: "<picture>",
      c: "<src>",
      d: "<image>",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 17,
    question: "Which method is used to parse a JSON string in JavaScript?",
    options: {
      a: "JSON.parse()",
      b: "JSON.stringify()",
      c: "parseJSON()",
      d: "parse()",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 18,
    question: "Which of the following is not a valid JavaScript variable name?",
    options: {
      a: "_name",
      b: "2name",
      c: "name2",
      d: "$name",
    },
    answer: "b",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 19,
    question: "Which CSS property is used to change the text color?",
    options: {
      a: "font-color",
      b: "color",
      c: "text-color",
      d: "background-color",
    },
    answer: "b",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 20,
    question: "Which HTML tag is used to create a hyperlink?",
    options: {
      a: "<a>",
      b: "<link>",
      c: "<href>",
      d: "<hyperlink>",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 21,
    question: "Which operator is used to assign a value to a variable?",
    options: {
      a: "==",
      b: "=",
      c: "===",
      d: "!=",
    },
    answer: "b",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 22,
    question: "Which method is used to remove the last element from an array?",
    options: {
      a: "pop()",
      b: "push()",
      c: "shift()",
      d: "unshift()",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 23,
    question: "Which of the following is a valid way to declare a function?",
    options: {
      a: "function myFunc() {}",
      b: "def myFunc() {}",
      c: "func myFunc() {}",
      d: "function:myFunc() {}",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 24,
    question: "Which HTML tag is used to define a table row?",
    options: {
      a: "<tr>",
      b: "<td>",
      c: "<th>",
      d: "<row>",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 25,
    question: "Which CSS property is used to set the background color?",
    options: {
      a: "background-color",
      b: "color",
      c: "bgcolor",
      d: "background",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 26,
    question:
      "Which of the following is not a looping structure in JavaScript?",
    options: {
      a: "for",
      b: "while",
      c: "foreach",
      d: "do...while",
    },
    answer: "c",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 27,
    question: "Which HTML tag is used to define emphasized text?",
    options: {
      a: "<strong>",
      b: "<em>",
      c: "<i>",
      d: "<b>",
    },
    answer: "b",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 28,
    question: "Which method is used to add an element at the end of an array?",
    options: {
      a: "push()",
      b: "pop()",
      c: "shift()",
      d: "unshift()",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 29,
    question: "Which of the following is a block-level element in HTML?",
    options: {
      a: "<span>",
      b: "<div>",
      c: "<a>",
      d: "<img>",
    },
    answer: "b",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 30,
    question: "Which CSS property is used to set the font size?",
    options: {
      a: "font-size",
      b: "text-size",
      c: "size",
      d: "font",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 31,
    question: "Which JavaScript method is used to select an element by ID?",
    options: {
      a: "getElementById()",
      b: "querySelectorAll()",
      c: "getElementsByClassName()",
      d: "getElementByTagName()",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 32,
    question: "Which HTML tag is used to define a list item?",
    options: {
      a: "<li>",
      b: "<ul>",
      c: "<ol>",
      d: "<item>",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 33,
    question: "Which of the following is not a valid CSS unit?",
    options: {
      a: "px",
      b: "em",
      c: "pt",
      d: "kg",
    },
    answer: "d",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 34,
    question:
      "Which method is used to convert a string to lowercase in JavaScript?",
    options: {
      a: "toLowerCase()",
      b: "toUpperCase()",
      c: "lowerCase()",
      d: "convertLower()",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 35,
    question: "Which HTML tag is used to define a form?",
    options: {
      a: "<form>",
      b: "<input>",
      c: "<fieldset>",
      d: "<label>",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 36,
    question: "Which CSS property is used to make text bold?",
    options: {
      a: "font-weight",
      b: "font-style",
      c: "bold",
      d: "text-weight",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 37,
    question:
      "Which JavaScript method is used to join array elements into a string?",
    options: {
      a: "join()",
      b: "concat()",
      c: "split()",
      d: "merge()",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 38,
    question: "Which HTML tag is used to define a heading?",
    options: {
      a: "<h1>",
      b: "<head>",
      c: "<header>",
      d: "<heading>",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 39,
    question:
      "Which CSS property is used to set the spacing between lines of text?",
    options: {
      a: "line-height",
      b: "letter-spacing",
      c: "word-spacing",
      d: "spacing",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 40,
    question:
      "Which JavaScript method is used to remove the first element from an array?",
    options: {
      a: "shift()",
      b: "pop()",
      c: "unshift()",
      d: "splice()",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 41,
    question: "Which HTML tag is used to define a dropdown list?",
    options: {
      a: "<select>",
      b: "<dropdown>",
      c: "<option>",
      d: "<list>",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 42,
    question: "Which CSS property is used to set the width of an element?",
    options: {
      a: "width",
      b: "size",
      c: "element-width",
      d: "max-width",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 43,
    question:
      "Which JavaScript method is used to add an element at the beginning of an array?",
    options: {
      a: "unshift()",
      b: "push()",
      c: "shift()",
      d: "pop()",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 44,
    question: "Which HTML tag is used to define a paragraph?",
    options: {
      a: "<p>",
      b: "<para>",
      c: "<paragraph>",
      d: "<text>",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 45,
    question:
      "Which CSS property is used to set the left margin of an element?",
    options: {
      a: "margin-left",
      b: "padding-left",
      c: "left-margin",
      d: "margin",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 46,
    question: "Which JavaScript method is used to find the length of a string?",
    options: {
      a: "length",
      b: "size()",
      c: "count()",
      d: "getLength()",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 47,
    question: "Which HTML tag is used to define a checkbox?",
    options: {
      a: "<input type='checkbox'>",
      b: "<checkbox>",
      c: "<input type='check'>",
      d: "<check>",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 48,
    question: "Which CSS property is used to set the border of an element?",
    options: {
      a: "border",
      b: "border-style",
      c: "border-width",
      d: "border-color",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 49,
    question:
      "Which JavaScript method is used to convert a number to a string?",
    options: {
      a: "toString()",
      b: "parseInt()",
      c: "String()",
      d: "numberToString()",
    },
    answer: "a",
    imageUrl: null,
  },
  {
    testId: "test001",
    id: 50,
    question: "Which HTML tag is used to define a line break?",
    options: {
      a: "<br>",
      b: "<lb>",
      c: "<break>",
      d: "<newline>",
    },
    answer: "a",
    imageUrl: null,
  },
];

export const tests = [
  { testId: "test001", title: "Frontend Developer Interview" },
];
